import { IAppItem, ITenantInfo } from '../interfaces';

/**
 * MASTER ECOSYSTEM CONFIGURATION REGISTRY
 * Linked directly to the LordIcon animated GIF files in public/icons/ and AppLauncher UI
 */
export const HOTEL_OS_APPS: IAppItem[] = [
  {
    id: 'stay-os',
    name: 'Stay OS',
    shortName: 'PMS & Desk',
    tagline: 'Property Management System',
    description: 'Front desk operations, 14-day room allocation matrix grid, reservation wizard, housekeeping kanban, and folio engines.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5174,
    url: 'https://stay.namios.app',
    devCommand: 'cd hotelos-stay-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #007AFF 0%, #00C6FF 100%)',
    iconColor: '#007AFF',
    gradientBorder: 'from-blue-500/20 via-indigo-500/20 to-sky-500/20',
    badge: 'Core',
    badgeColor: 'bg-black text-white',
    badgeText: 'Property Management',
    metrics: {
      label: 'Rooms Tracked',
      value: '142 Active',
    },
    roles: ['Front Desk Agent', 'General Manager', 'Housekeeping Lead'],
    features: [
      'Room Allocation Grid Matrix',
      'Quick Reservation Wizard',
      'Housekeeping Kanban Lanes',
      'Automated Folio Engine',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/stay-os',
    lordIconSrc: '/icons/stay.gif',
  },
  {
    id: 'dine-os',
    name: 'Dine OS',
    shortName: 'F&B & POS',
    tagline: 'Restaurant & Kitchen Workspace',
    description: 'Interactive floor seating canvas, live dual-pane POS order cart, kitchen queue kanban with rush indicators, and room bill transfers.',
    category: 'DINING',
    status: 'OPERATIONAL',
    port: 5175,
    url: 'https://dine.namios.app',
    devCommand: 'cd hotelos-dine-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #FF6B00 0%, #FFA800 100%)',
    iconColor: '#FF6B00',
    gradientBorder: 'from-rose-500/20 via-orange-500/20 to-amber-500/20',
    badge: 'Live',
    badgeColor: 'bg-[#FF6B00] text-white',
    badgeText: 'Restaurant & POS',
    metrics: {
      label: 'Kitchen Queue',
      value: '18 Orders',
    },
    roles: ['F&B Manager', 'Kitchen Chef', 'POS Cashier', 'Table Captain'],
    features: [
      'Interactive Seating Floor Plan',
      'Live POS Cart & Billing',
      'Rush Priority Kitchen Queue',
      'Room Bill Transfer Engine',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/dine-os',
    lordIconSrc: '/icons/dine.gif',
  },
  {
    id: 'people-hr',
    name: 'People (HR)',
    shortName: 'Staff & HR',
    tagline: 'Staff Roster, Attendance & Payroll',
    description: 'Shift scheduling, employee attendance tracking, payroll processing, leave management, and staff performance metrics.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5176,
    url: 'https://people.namios.app',
    devCommand: 'cd hotelos-stay-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #9333EA 0%, #C084FC 100%)',
    iconColor: '#9333EA',
    gradientBorder: 'from-purple-500/20 via-fuchsia-500/20 to-violet-500/20',
    badge: 'HR',
    badgeColor: 'bg-[#007AFF] text-white',
    badgeText: 'Staff & HR',
    metrics: {
      label: 'Staff Active',
      value: '34 Online',
    },
    roles: ['HR Manager', 'Department Lead', 'General Manager'],
    features: [
      'Shift & Roster Scheduling',
      'Biometric & Mobile Attendance',
      'Payroll & Tip Calculator',
      'Staff Leave Requests',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/people-hr',
    lordIconSrc: '/icons/people.gif',
  },
  {
    id: 'super-admin',
    name: 'Super Admin',
    shortName: 'Platform Control',
    tagline: 'Tenant & Subscription Control',
    description: 'Platform management dashboard tracking tenant onboarding, subscription tiers, MRR analytics, and system audit logs.',
    category: 'ADMIN',
    status: 'OPERATIONAL',
    port: 5173,
    url: 'https://admin.namios.app',
    devCommand: 'cd hotelos-super-admin && pnpm dev',
    iconBg: 'linear-gradient(135deg, #1C1C1E 0%, #3A3A3C 100%)',
    iconColor: '#16A34A',
    gradientBorder: 'from-emerald-500/20 via-teal-500/20 to-green-500/20',
    badge: 'Admin',
    badgeColor: 'bg-slate-200 text-slate-700',
    badgeText: 'Platform Control',
    metrics: {
      label: 'MRR Growth',
      value: '+24.5%',
    },
    roles: ['Super Admin', 'Platform Owner', 'Billing Manager'],
    features: [
      'Client / Tenant Directory',
      'Plan Tier & Proration Switcher',
      'Security Audit Trail Logs',
      'System-Wide Diagnostics',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/super-admin',
    lordIconSrc: '/icons/admin.gif',
  },
  {
    id: 'payments-os',
    name: 'Payments OS',
    shortName: 'Billing & Gateway',
    tagline: 'Multi-Currency Terminal & Invoicing',
    description: 'Payment gateway integrations, card terminal processing, room folio billing, cash drawer reconciliations, and tax calculations.',
    category: 'ADMIN',
    status: 'OPERATIONAL',
    port: 4000,
    url: 'https://payments.namios.app',
    devCommand: 'cd hotel-os-be && npm run dev',
    iconBg: 'linear-gradient(135deg, #00C7BE 0%, #30B0C7 100%)',
    iconColor: '#EA580C',
    gradientBorder: 'from-amber-500/20 via-orange-500/20 to-red-500/20',
    badge: 'Gateway',
    badgeColor: 'bg-[#007AFF] text-white',
    badgeText: 'Payment Gateway',
    metrics: {
      label: 'Today Revenue',
      value: '$42,850',
    },
    roles: ['Finance Lead', 'Front Desk Cashier', 'General Manager'],
    features: [
      'Integrated Card Terminal',
      'Sri Lanka Tax (SSCL/VAT) Engine',
      'Multi-Currency Exchange Rates',
      'Shift Cashier Reconciliation',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/payments-os',
    lordIconSrc: '/icons/payments.gif',
  },
  {
    id: 'inventory-os',
    name: 'Inventory OS',
    shortName: 'Stock & POs',
    tagline: 'F&B Stock & Supplies Control',
    description: 'Real-time stock level tracking, kitchen ingredient usage, linen inventories, low-stock alerts, and purchase order creation.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5175,
    url: 'https://inventory.namios.app',
    devCommand: 'cd hotelos-dine-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #0891B2 0%, #06B6D4 100%)',
    iconColor: '#0891B2',
    gradientBorder: 'from-cyan-500/20 via-sky-500/20 to-blue-500/20',
    badge: 'Stock',
    badgeColor: 'bg-slate-200 text-slate-700',
    badgeText: 'Stock Engine',
    metrics: {
      label: 'Items Tracked',
      value: '1,420 Items',
    },
    roles: ['Store Manager', 'F&B Manager', 'Kitchen Chef'],
    features: [
      'Real-Time Stock Audits',
      'Automated Low-Stock Alerts',
      'Supplier Purchase Orders (PO)',
      'Recipe Ingredient Deduction',
    ],
    isFavorite: true,
    docUrl: 'https://docs.namios.app/inventory-os',
    lordIconSrc: '/icons/inventory.gif',
  },
  {
    id: 'nami-ai',
    name: 'Nami AI',
    shortName: 'AI Concierge',
    tagline: 'Smart Assistant & Messaging',
    description: 'AI Guest Concierge, Assistant & Smart Messaging across Guest Portals and Front Desk.',
    category: 'OPERATIONS',
    status: 'BETA',
    port: 5176,
    url: 'https://ai.namios.app',
    devCommand: 'cd hotelos-stay-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #AF52DE 0%, #FF2D55 100%)',
    iconColor: '#AF52DE',
    gradientBorder: 'from-pink-500/20 via-purple-500/20 to-rose-500/20',
    badge: 'AI Beta',
    badgeColor: 'bg-[#007AFF] text-white',
    badgeText: 'AI Concierge',
    metrics: {
      label: 'Guest Queries',
      value: '99.4% Accurate',
    },
    roles: ['Front Desk', 'Guest Concierge', 'Duty Manager'],
    features: [
      'Automated Guest Chat Concierge',
      'Room Upgrade Suggestions',
      'Instant Multilingual Translations',
      'Smart WhatsApp Draft Generator',
    ],
    isFavorite: false,
    docUrl: 'https://docs.namios.app/nami-ai',
    lordIconSrc: '/icons/stay.gif',
  },
  {
    id: 'public-web',
    name: 'Booking Engine',
    shortName: 'Guest Portal',
    tagline: 'Public Guest Direct Booking',
    description: 'Public Guest Direct Booking & Hotel Web Portal for direct room reservations and rates.',
    category: 'PUBLIC',
    status: 'OPERATIONAL',
    port: 3000,
    url: 'https://booking.namios.app',
    devCommand: 'cd hotel-os-public-web && pnpm dev',
    iconBg: 'linear-gradient(135deg, #34C759 0%, #30D158 100%)',
    iconColor: '#34C759',
    gradientBorder: 'from-green-500/20 via-emerald-500/20 to-teal-500/20',
    badge: 'Public',
    badgeColor: 'bg-[#34C759] text-white',
    badgeText: 'Direct Booking',
    metrics: {
      label: 'Direct Conversion',
      value: '4.8% Rate',
    },
    roles: ['Public Guests', 'Marketing Lead', 'Revenue Manager'],
    features: [
      'Direct Commission-Free Bookings',
      'Real-Time Room Calendar & Rates',
      'Special Promo Code Engine',
      'Instant WhatsApp Inquiry Integration',
    ],
    isFavorite: false,
    docUrl: 'https://docs.namios.app/guest-portal',
    lordIconSrc: '/icons/stay.gif',
  },
];

export const DEFAULT_TENANTS: ITenantInfo[] = [
  {
    id: 'tenant-01',
    name: 'Grand Palace Hotel Colombo',
    city: 'Colombo',
    country: 'Sri Lanka',
    roomsCount: 142,
    tier: 'Enterprise',
  },
  {
    id: 'tenant-02',
    name: 'Sun & Sand Beach Resort',
    city: 'Galle',
    country: 'Sri Lanka',
    roomsCount: 68,
    tier: 'Professional',
  },
  {
    id: 'tenant-03',
    name: 'Cinnamon Hill Tea Estate Villa',
    city: 'Nuwara Eliya',
    country: 'Sri Lanka',
    roomsCount: 24,
    tier: 'Starter',
  },
];
