import { IAppItem, ITenantInfo } from '../interfaces';

/**
 * MASTER ECOSYSTEM CONFIGURATION REGISTRY
 * Linked directly to the 6 LordIcon animated GIF files in public/icons/
 */
export const HOTEL_OS_APPS: IAppItem[] = [
  {
    id: 'stay-os',
    name: 'Stay OS',
    shortName: 'PMS & Desk',
    tagline: 'Property Management System',
    description: 'Front desk operations, 14-day room allocation matrix grid, reservation wizard, housekeeping kanban, and folio engines.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5174,
    url: 'https://stay.namios.app/',
    devCommand: 'cd hotelos-stay-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)',
    iconColor: '#2563eb',
    gradientBorder: 'from-blue-500/20 via-indigo-500/20 to-sky-500/20',
    badgeText: 'Port 5174',
    metrics: {
      label: 'Rooms Tracked',
      value: '142 Active',
    },
    roles: ['Front Desk Agent', 'General Manager', 'Housekeeping Lead'],
    features: [
      'Room Allocation Grid Matrix',
      'Quick Reservation Wizard',
      'Housekeeping Kanban Lanes',
      'Automated Folio Engine',
    ],
    isFavorite: true,
    docUrl: 'https://docs.stay.namios.app/',
    lordIconSrc: '/icons/stay.gif',
  },
  {
    id: 'dine-os',
    name: 'Dine OS',
    shortName: 'F&B & POS',
    tagline: 'Restaurant & Kitchen Workspace',
    description: 'Interactive floor seating canvas, live dual-pane POS order cart, kitchen queue kanban with rush indicators, and room bill transfers.',
    category: 'DINING',
    status: 'OPERATIONAL',
    port: 5175,
    url: 'https://dine.namios.app/',
    devCommand: 'cd hotelos-dine-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)',
    iconColor: '#dc2626',
    gradientBorder: 'from-rose-500/20 via-orange-500/20 to-amber-500/20',
    badgeText: 'Port 5175',
    metrics: {
      label: 'Kitchen Queue',
      value: '18 Orders',
    },
    roles: ['F&B Manager', 'Kitchen Chef', 'POS Cashier', 'Table Captain'],
    features: [
      'Interactive Seating Floor Plan',
      'Live POS Cart & Billing',
      'Rush Priority Kitchen Queue',
      'Room Bill Transfer Engine',
    ],
    isFavorite: true,
    docUrl: 'https://docs.dine.namios.app/',
    lordIconSrc: '/icons/dine.gif',
  },
  {
    id: 'people-hr',
    name: 'People (HR)',
    shortName: 'Staff & HR',
    tagline: 'Staff Roster, Attendance & Payroll',
    description: 'Shift scheduling, employee attendance tracking, payroll processing, leave management, and staff performance metrics.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5176,
    url: 'https://people.namios.app/',
    devCommand: 'cd hotelos-stay-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)',
    iconColor: '#9333ea',
    gradientBorder: 'from-purple-500/20 via-fuchsia-500/20 to-violet-500/20',
    badgeText: 'HR Module',
    metrics: {
      label: 'Staff Active',
      value: '34 Online',
    },
    roles: ['HR Manager', 'Department Lead', 'General Manager'],
    features: [
      'Shift & Roster Scheduling',
      'Biometric & Mobile Attendance',
      'Payroll & Tip Calculator',
      'Staff Leave Requests',
    ],
    isFavorite: true,
    docUrl: 'https://docs.people.namios.app/',
    lordIconSrc: '/icons/people.gif',
  },
  {
    id: 'super-admin',
    name: 'Admin',
    shortName: 'Platform Control',
    tagline: 'Tenant & Subscription Control',
    description: 'Platform management dashboard tracking tenant onboarding, subscription tiers, MRR analytics, and system audit logs.',
    category: 'ADMIN',
    status: 'OPERATIONAL',
    port: 5173,
    url: 'https://admin.namios.app/',
    devCommand: 'cd hotelos-super-admin && pnpm dev',
    iconBg: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    iconColor: '#16a34a',
    gradientBorder: 'from-emerald-500/20 via-teal-500/20 to-green-500/20',
    badgeText: 'Port 5173',
    metrics: {
      label: 'MRR Growth',
      value: '+24.5%',
    },
    roles: ['Super Admin', 'Platform Owner', 'Billing Manager'],
    features: [
      'Client / Tenant Directory',
      'Plan Tier & Proration Switcher',
      'Security Audit Trail Logs',
      'System-Wide Diagnostics',
    ],
    isFavorite: true,
    docUrl: 'https://docs.admin.namios.app/',
    lordIconSrc: '/icons/admin.gif',
  },
  {
    id: 'payments-os',
    name: 'Payments',
    shortName: 'Billing & Gateway',
    tagline: 'Multi-Currency Terminal & Invoicing',
    description: 'Payment gateway integrations, card terminal processing, room folio billing, cash drawer reconciliations, and tax calculations.',
    category: 'ADMIN',
    status: 'OPERATIONAL',
    port: 4000,
    url: 'https://payments.namios.app/',
    devCommand: 'cd hotel-os-be && npm run dev',
    iconBg: 'linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)',
    iconColor: '#ea580c',
    gradientBorder: 'from-amber-500/20 via-orange-500/20 to-red-500/20',
    badgeText: 'Gateway',
    metrics: {
      label: 'Today Revenue',
      value: '$42,850',
    },
    roles: ['Finance Lead', 'Front Desk Cashier', 'General Manager'],
    features: [
      'Integrated Card Terminal',
      'Sri Lanka Tax (SSCL/VAT) Engine',
      'Multi-Currency Exchange Rates',
      'Shift Cashier Reconciliation',
    ],
    isFavorite: true,
    docUrl: 'https://docs.payments.namios.app/',
    lordIconSrc: '/icons/payments.gif',
  },
  {
    id: 'inventory-os',
    name: 'Inventory',
    shortName: 'Stock & POs',
    tagline: 'F&B Stock & Supplies Control',
    description: 'Real-time stock level tracking, kitchen ingredient usage, linen inventories, low-stock alerts, and purchase order creation.',
    category: 'OPERATIONS',
    status: 'OPERATIONAL',
    port: 5175,
    url: 'https://inventory.namios.app/',
    devCommand: 'cd hotelos-dine-os && pnpm dev',
    iconBg: 'linear-gradient(135deg, #ecfeff 0%, #cffaff 100%)',
    iconColor: '#0891b2',
    gradientBorder: 'from-cyan-500/20 via-sky-500/20 to-blue-500/20',
    badgeText: 'Stock Engine',
    metrics: {
      label: 'Items Tracked',
      value: '1,420 Items',
    },
    roles: ['Store Manager', 'F&B Manager', 'Kitchen Chef'],
    features: [
      'Real-Time Stock Audits',
      'Automated Low-Stock Alerts',
      'Supplier Purchase Orders (PO)',
      'Recipe Ingredient Deduction',
    ],
    isFavorite: true,
    docUrl: 'https://docs.inventory.namios.app/',
    lordIconSrc: '/icons/inventory.gif',
  },
];

export const DEFAULT_TENANTS: ITenantInfo[] = [
  {
    id: 'tenant-01',
    name: 'Grand Palace Hotel Colombo',
    city: 'Colombo',
    country: 'Sri Lanka',
    roomsCount: 142,
    tier: 'Enterprise',
  },
  {
    id: 'tenant-02',
    name: 'Sun & Sand Beach Resort',
    city: 'Galle',
    country: 'Sri Lanka',
    roomsCount: 68,
    tier: 'Professional',
  },
  {
    id: 'tenant-03',
    name: 'Cinnamon Hill Tea Estate Villa',
    city: 'Nuwara Eliya',
    country: 'Sri Lanka',
    roomsCount: 24,
    tier: 'Starter',
  },
];
